[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Sécurité par défaut
[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Frame-Options = "DENY"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Empêcher l’indexation
[context.deploy-preview.headers]  # PR / previews
  [[context.deploy-preview.headers.values]]
  X-Robots-Tag = "noindex, nofollow"

[context.branch-deploy.headers]
  [[context.branch-deploy.headers.values]]
  X-Robots-Tag = "noindex, nofollow"

# Optionnel : CSP stricte (à activer quand tout est local)
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self'; font-src 'self'; script-src 'self'; base-uri 'self'; form-action 'self'"
